package com.payrecover.payrecoverai.entity;

/**
 * All the states a payment can be in, in our simplified prototype.
 *
 * SUCCESS       -> payment went through on the very first attempt.
 * FAILED        -> payment failed and has NOT been retried yet.
 * RECOVERED     -> payment failed, was retried, and the retry succeeded.
 * FAILED_AGAIN  -> payment failed, was retried, and the retry also failed.
 *
 * Note: In Phase 1-3 these statuses are just data (mostly pre-generated by the
 * synthetic data seeder). From Phase 5-7 onward, the AI + Policy Engine +
 * Recovery Simulator will be what actually MOVES a payment from FAILED to
 * RECOVERED or FAILED_AGAIN in real time.
 */
public enum PaymentStatus {
    SUCCESS,
    FAILED,
    RECOVERED,
    FAILED_AGAIN
}
